# Generated by Django 4.2.16 on 2025-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Raw JSON Payload'),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Raw JSON Payload'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='api_response',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Response'),
        ),
        migrations.AlterField(
            model_name='report',
            name='api_response',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Response'),
        ),
    ]
