# Generated by Django 4.2.16 on 2025-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_historicalreport_lead_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
    ]
