# Generated by Django 4.2.16 on 2025-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_historicalreport_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='id_ltw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LTW ID'),
        ),
        migrations.AddField(
            model_name='report',
            name='id_ltw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LTW ID'),
        ),
    ]
